const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/world-impact/');await page.waitForSelector('.event-card');await page.screenshot({path:'evidence/desktop.png',fullPage:true});
 const asserts=[];const ok=(condition,label)=>{if(!condition)throw Error(label);asserts.push(label)};
 ok(await page.locator('.event-card').count()===3,'three cases loaded');
 ok(await page.locator('.card-meta').first().textContent()==='個人關聯待確認','no implicit personal impact');
 for(let i=0;i<3;i++){await page.locator('.event-card').nth(i).click();await page.locator('#detail').waitFor({state:'visible'});ok(await page.locator('.flow li').count()===3,'pathway opens '+i);await page.locator('#back').click();await page.locator('#detail').waitFor({state:'hidden'})}
 await page.locator('.event-card').first().click();await page.locator('#conditions select').nth(0).selectOption('yes');await page.locator('#conditions select').nth(1).selectOption('yes');await page.getByRole('button',{name:'儲存我的情境'}).click();await page.locator('#save-case').check();await page.locator('#ack-case').check();await page.locator('#back').click();await page.reload();await page.locator('.event-card').first().click();ok(await page.locator('#conditions select').first().inputValue()==='yes','localStorage restored');ok(await page.locator('#save-case').isChecked(),'checklist restored');
 await page.locator('#conditions select').first().selectOption('no');await page.locator('#cancel-conditions').click();ok(await page.locator('#conditions select').first().inputValue()==='yes','cancel restores saved conditions');await page.locator('#conditions select').first().selectOption('no');ok((await page.locator('#match').textContent()).includes('未見直接關聯'),'no-match state');await page.locator('#close-detail').click();
 await page.locator('[data-filter=assets]').click();ok((await page.locator('#cards').textContent()).includes('還沒有案例'),'no-data category');await page.locator('[data-all]').click();
 await page.locator('#settings').click();await page.locator('#interest').selectOption('travel');await page.getByRole('button',{name:'取消',exact:true}).click();ok(await page.locator('.event-card').count()===3,'preferences cancel');
 await page.locator('#load3d').click();await page.waitForFunction(()=>!document.querySelector('#load3d').disabled);ok(await page.locator('canvas').count()===1,'actual GLB WebGL loaded');await page.screenshot({path:'evidence/desktop-3d.png',fullPage:true});await page.locator('#load3d').click();ok(await page.locator('canvas').count()===0,'3D disposed to static');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'evidence/mobile.png',fullPage:true});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px no horizontal overflow');await page.locator('.event-card').nth(2).click();await page.screenshot({path:'evidence/mobile-detail.png',fullPage:true});ok(await page.locator('.source').count()===2,'official source links');await page.keyboard.press('Escape');ok(!await page.locator('#detail').isVisible(),'Escape closes modal');
 const fail=await browser.newPage();await fail.route('**/events.json',r=>r.abort());await fail.goto('http://127.0.0.1:8765/world-impact/');await fail.locator('#retry').waitFor();ok((await fail.locator('#cards').textContent()).includes('無法載入'),'data error state');await fail.unroute('**/events.json');await fail.locator('#retry').click();await fail.locator('.event-card').first().waitFor();ok(await fail.locator('.event-card').count()===3,'data retry recovers');
 const noGL=await browser.newPage({reducedMotion:'reduce'});await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...a){return type.includes('webgl')?null:original.call(this,type,...a)}});await noGL.goto('http://127.0.0.1:8765/world-impact/');await noGL.locator('.event-card').first().waitFor();ok((await noGL.locator('#visual-status').textContent()).includes('低動效'),'reduced motion default');await noGL.locator('#load3d').click();await noGL.waitForFunction(()=>!document.querySelector('#load3d').disabled);ok((await noGL.locator('#visual-status').textContent()).includes('不支援'),'WebGL fallback');await noGL.locator('.event-card').first().click();ok(await noGL.locator('#detail').isVisible(),'WebGL fallback preserves events');
 const future=await browser.newPage();await future.clock.install({time:new Date('2026-10-14T00:00:00Z')});await future.goto('http://127.0.0.1:8765/world-impact/');await future.locator('.event-card').nth(2).waitFor();ok((await future.locator('.event-card').nth(2).textContent()).includes('日期已過'),'Belgium expiry becomes historical');
 ok(errors.length===0,'no page exceptions');fs.writeFileSync('evidence/qa.json',JSON.stringify({asserts,errors,passed:asserts.length,date:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:asserts.length,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
